### ISSUE TITLE
公式块感觉不是很友好

### ISSUE THREAD

**Issue by ghost** [luokangyuan/typora-theme-chineseStyle#2]
感觉主题风格十分不错，给人一种沉静的感觉，不过我这里用公式块的时候感觉不是很友好，编辑的时候字体看不清楚，感觉您是否可以调整一下，仅仅作为个人建议，谢谢！

**Comment by luokangyuan** [comment]
方便附上你常用的一些公式块的markdown吗，我调整一下显示格式，谢谢

**Comment by ghost** [comment]
emm，大概效果是这样，不必客气








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Be All You Can Be"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月30日(星期六) 下午3:28
收件人:&nbsp;"luokangyuan/typora-theme-chineseStyle"<typora-theme-chineseStyle@noreply.github.com&gt;;
抄送:&nbsp;"f(c)"<cfunction@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [luokangyuan/typora-theme-chineseStyle] 公式块感觉不是很友好 (#2)





 
方便附上你常用的一些公式块的markdown吗，我调整一下显示格式，谢谢

**Comment by ghost** [comment]
看了一下好像github上显示不出图片，不知您邮箱里收没收到，已经发送过去了

**Comment by luokangyuan** [comment]
邮件里也没有图片，方便直接把markdown文件发我吗，我打开就能调整样式了

**Comment by ghost** [comment]
> 邮件里也没有图片，方便直接把markdown文件发我吗，我打开就能调整样式了

这就比较奇怪了，我图片和文件都发在邮件里了，那我把代码发在这里吧
\begin{array}{l}{C_n} = {a_1}{b_1} + ({a_1}{b_2} + {a_2}{b_1}) + .........({a_1}{b_n} + {a_2}{b_{n - 1}} + ......{a_n}{b_1})\\ = {a_1}(\sum\limits_{i = 1}^n {{b_i}} ) + {a_2}\sum\limits_{i = 1}^{n - 1} {{b_i}}  + .........{a_n}{b_1}\\set{B_{\rm{n}}} = B - {\beta _n},{\beta _n} \to 0,\\{C_n} = {A_n}B - {\gamma _n},{\gamma _n} = \sum\limits_{i = 1}^n {{a_i}{\beta _{n + 1}}} ,\\\left| {{\gamma _n}} \right| \le \left| {{a_1}{\beta _n} + ......{a_{n - N}}{\beta _{N + 1}}} \right| + \left| {{a_{n - N + 1}}{\beta _N} + {a_n}{\beta _1}} \right|\\ < \varepsilon M + \left| {\left| {{a_{n - N + 1}}{\beta _N} + {a_n}{\beta _1}} \right|} \right|\end{array}

**Comment by luokangyuan** [comment]
> > 邮件里也没有图片，方便直接把markdown文件发我吗，我打开就能调整样式了
> 
> 这就比较奇怪了，我图片和文件都发在邮件里了，那我把代码发在这里吧
> \begin{array}{l}{C_n} = {a_1}{b_1} + ({a_1}{b_2} + {a_2}{b_1}) + .........({a_1}{b_n} + {a_2}{b_{n - 1}} + ......{a_n}{b_1})\ = {a_1}(\sum\limits_{i = 1}^n {{b_i}} ) + {a_2}\sum\limits_{i = 1}^{n - 1} {{b_i}} + .........{a_n}{b_1}\set{B_{\rm{n}}} = B - {\beta _n},{\beta _n} \to 0,\{C_n} = {A_n}B - {\gamma _n},{\gamma _n} = \sum\limits_{i = 1}^n {{a_i}{\beta _{n + 1}}} ,\\left| {{\gamma _n}} \right| \le \left| {{a_1}{\beta _n} + ......{a_{n - N}}{\beta _{N + 1}}} \right| + \left| {{a_{n - N + 1}}{\beta _N} + {a_n}{\beta _1}} \right|\ < \varepsilon M + \left| {\left| {{a_{n - N + 1}}{\beta _N} + {a_n}{\beta _1}} \right|} \right|\end{array}

好的，已经收到，正在调整ing

**Comment by luokangyuan** [comment]
> > 邮件里也没有图片，方便直接把markdown文件发我吗，我打开就能调整样式了
> 
> 这就比较奇怪了，我图片和文件都发在邮件里了，那我把代码发在这里吧
> \begin{array}{l}{C_n} = {a_1}{b_1} + ({a_1}{b_2} + {a_2}{b_1}) + .........({a_1}{b_n} + {a_2}{b_{n - 1}} + ......{a_n}{b_1})\ = {a_1}(\sum\limits_{i = 1}^n {{b_i}} ) + {a_2}\sum\limits_{i = 1}^{n - 1} {{b_i}} + .........{a_n}{b_1}\set{B_{\rm{n}}} = B - {\beta _n},{\beta _n} \to 0,\{C_n} = {A_n}B - {\gamma _n},{\gamma _n} = \sum\limits_{i = 1}^n {{a_i}{\beta _{n + 1}}} ,\\left| {{\gamma _n}} \right| \le \left| {{a_1}{\beta _n} + ......{a_{n - N}}{\beta _{N + 1}}} \right| + \left| {{a_{n - N + 1}}{\beta _N} + {a_n}{\beta _1}} \right|\ < \varepsilon M + \left| {\left| {{a_{n - N + 1}}{\beta _N} + {a_n}{\beta _1}} \right|} \right|\end{array}

![image-20200530165923314](http://image.luokangyuan.com/2020-05-30-090259.png)

**Comment by luokangyuan** [comment]
![image-20200530165923314](http://image.luokangyuan.com/2020-05-30-090259.png)
作了如上修改

**Comment by ghost** [comment]
![2T9F)K 3P7M9JPBBHB2D%8W](https://user-images.githubusercontent.com/65492457/83324565-aa0e1600-a298-11ea-93d3-7a4ceac6a02b.png)
emm，我这里显示的感觉还是不太友好，我这里是Windows系统，感觉或许不太一样emm，，

**Comment by ghost** [comment]
图片又没发出去。。。

**Comment by ghost** [comment]
您稍等一下，我创建个项目里面放图片

**Comment by luokangyuan** [comment]
> 您稍等一下，我创建个项目里面放图片

已经看到了，周一我去公司用windows系统看一下，改一下把，我用mac看是可以的

**Comment by ghost** [comment]
> > 您稍等一下，我创建个项目里面放图片
> 
> 已经看到了，周一我去公司用windows系统看一下，改一下把，我用mac看是可以的

好的

**Comment by luokangyuan** [comment]
> > > 您稍等一下，我创建个项目里面放图片
> > 
> > 
> > 已经看到了，周一我去公司用windows系统看一下，改一下把，我用mac看是可以的
> 
> 好的

你这是最新下载的，不是的话麻烦下载一下最新的试试，最近一直也有修改优化

**Comment by ghost** [comment]
> > > > 您稍等一下，我创建个项目里面放图片
> > > 
> > > 
> > > 已经看到了，周一我去公司用windows系统看一下，改一下把，我用mac看是可以的
> > 
> > 
> > 好的
> 
> 你这是最新下载的，不是的话麻烦下载一下最新的试试，最近一直也有修改优化

这里我刚刚下载的是最新的，emm，但是感觉Windows平台确实不一样，不过源代码模式的话我这里看已经没有任何看不清的地方了，我最近会一直关注您的主题的，祝一切顺利！（这次图片应该是传上来了吧）
[`https://github.com/c-function/tupian/blob/master/2T9F)K%5D3P7M9JPBBHB2D%258W.png`](https://github.com/c-function/tupian/blob/master/2T9F)K%5D3P7M9JPBBHB2D%258W.png)

**Comment by ghost** [comment]
https://github.com/c-function/tupian/blob/master/2T9F)K%5D3P7M9JPBBHB2D%258W.png
得，刚才又没发出去，不知哪里搞错了
