### ISSUE TITLE
左侧当前文件看不到名字

### ISSUE THREAD

**Issue by heyliyh** [luokangyuan/typora-theme-chineseStyle#7]
![image](https://user-images.githubusercontent.com/26408355/83792276-69196580-a6cd-11ea-90a5-ed0b68da2341.png)

**Comment by luokangyuan** [comment]
感谢你的提出，已修改
![image](https://user-images.githubusercontent.com/20436954/83964397-7312b280-a8df-11ea-8048-b1425ec73d2b.png)
